/*
**	$Id$
**	Generated by IDLTool 51.3
**	Do not edit
**
**	AutoInit stub for xpkGZIP
**
**	(C) Copyright 2003-2004 Amiga, Inc.
**	    All Rights Reserved
*/

#include <xpk/xpksub.h>

#include <interfaces/xpkGZIP.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

__attribute__((weak)) struct XpkSubBase * XpkSubBase = NULL;

void __init_xpkGZIP_base(void) __attribute__((constructor));
void __exit_xpkGZIP_base(void) __attribute__((destructor));

/****************************************************************************/

void __init_xpkGZIP_base(void)
{
    if (XpkSubBase != NULL) return; /* Someone was quicker */
    XpkSubBase = IExec->OpenLibrary("xpkGZIP.library", 0L);
    assert(XpkSubBase != NULL);
}

/****************************************************************************/

void __exit_xpkGZIP_base(void)
{
    if (XpkSubBase) IExec->CloseLibrary((struct Library *)XpkSubBase);
}

/****************************************************************************/

