/*
** This file was automatically generated by fdtrans.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/xpkGZIP.h>
#include <proto/xpkGZIP.h>



STATIC ULONG stub_OpenPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Open(0);
}
struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, stub_OpenPPC };

STATIC ULONG stub_ClosePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return (ULONG) Self->Close();
}
struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, stub_ClosePPC };

STATIC ULONG stub_ExpungePPC(ULONG *regarray)
{
	return 0UL;
}
struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray)
{
	return 0UL;
}
struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static struct XpkInfo * stub_XpksPackerInfoPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct XpkSubIFace *Self = (struct XpkSubIFace *) ExtLib->MainIFace;

	return Self->XpksPackerInfo(
	);
}
struct EmuTrap stub_XpksPackerInfo = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_XpksPackerInfoPPC };

static LONG stub_XpksPackChunkPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct XpkSubIFace *Self = (struct XpkSubIFace *) ExtLib->MainIFace;

	return Self->XpksPackChunk(
		(struct XpkSubParams *)regarray[8]
	);
}
struct EmuTrap stub_XpksPackChunk = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_XpksPackChunkPPC };

static void stub_XpksPackFreePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct XpkSubIFace *Self = (struct XpkSubIFace *) ExtLib->MainIFace;

	Self->XpksPackFree(
		(struct XpkSubParams *)regarray[8]
	);
}
struct EmuTrap stub_XpksPackFree = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_XpksPackFreePPC };

static LONG stub_XpksPackResetPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct XpkSubIFace *Self = (struct XpkSubIFace *) ExtLib->MainIFace;

	return Self->XpksPackReset(
		(struct XpkSubParams *)regarray[8]
	);
}
struct EmuTrap stub_XpksPackReset = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_XpksPackResetPPC };

static LONG stub_XpksUnpackChunkPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct XpkSubIFace *Self = (struct XpkSubIFace *) ExtLib->MainIFace;

	return Self->XpksUnpackChunk(
		(struct XpkSubParams *)regarray[8]
	);
}
struct EmuTrap stub_XpksUnpackChunk = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_XpksUnpackChunkPPC };

static void stub_XpksUnpackFreePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct XpkSubIFace *Self = (struct XpkSubIFace *) ExtLib->MainIFace;

	Self->XpksUnpackFree(
		(struct XpkSubParams *)regarray[8]
	);
}
struct EmuTrap stub_XpksUnpackFree = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_XpksUnpackFreePPC };

ULONG VecTable68K[] = {
	(ULONG)&stub_Open,
	(ULONG)&stub_Close,
	(ULONG)&stub_Expunge,
	(ULONG)&stub_Reserved,
	(ULONG)&stub_XpksPackerInfo,
	(ULONG)&stub_XpksPackChunk,
	(ULONG)&stub_XpksPackFree,
	(ULONG)&stub_XpksPackReset,
	(ULONG)&stub_XpksUnpackChunk,
	(ULONG)&stub_XpksUnpackFree,
	(ULONG)-1
};
