
/* This file was generated by idltool 51.3. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>

#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef XPK_XPKSUB_H
#include <xpk/xpksub.h>
#endif

extern ULONG                VARARGS68K _XpkSub_Obtain(struct XpkSubIFace *);
extern ULONG                VARARGS68K _XpkSub_Release(struct XpkSubIFace *);
extern struct XpkInfo *     VARARGS68K _XpkSub_XpksPackerInfo(struct XpkSubIFace *);
extern LONG                 VARARGS68K _XpkSub_XpksPackChunk(struct XpkSubIFace *, struct XpkSubParams * xpar);
extern void                 VARARGS68K _XpkSub_XpksPackFree(struct XpkSubIFace *, struct XpkSubParams * xpar);
extern LONG                 VARARGS68K _XpkSub_XpksPackReset(struct XpkSubIFace *, struct XpkSubParams * xpar);
extern LONG                 VARARGS68K _XpkSub_XpksUnpackChunk(struct XpkSubIFace *, struct XpkSubParams * xpar);
extern void                 VARARGS68K _XpkSub_XpksUnpackFree(struct XpkSubIFace *, struct XpkSubParams * xpar);


static void *main_vectors[] = {
	(void *)_XpkSub_Obtain,
	(void *)_XpkSub_Release,
	(void *)NULL,
	(void *)NULL,
	(void *)_XpkSub_XpksPackerInfo,
	(void *)_XpkSub_XpksPackChunk,
	(void *)_XpkSub_XpksPackFree,
	(void *)_XpkSub_XpksPackReset,
	(void *)_XpkSub_XpksUnpackChunk,
	(void *)_XpkSub_XpksUnpackFree,
	(void *)-1
};

