#ifndef XPKGZIP_INTERFACE_DEF_H
#define XPKGZIP_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 51.3.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef XPK_XPKSUB_H
#include <xpk/xpksub.h>
#endif

struct XpkSubIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct XpkSubIFace *Self);
	ULONG APICALL (*Release)(struct XpkSubIFace *Self);
	void APICALL (*Expunge)(struct XpkSubIFace *Self);
	struct Interface * APICALL (*Clone)(struct XpkSubIFace *Self);
	struct XpkInfo * APICALL (*XpksPackerInfo)(struct XpkSubIFace *Self);
	LONG APICALL (*XpksPackChunk)(struct XpkSubIFace *Self, struct XpkSubParams * xpar);
	void APICALL (*XpksPackFree)(struct XpkSubIFace *Self, struct XpkSubParams * xpar);
	LONG APICALL (*XpksPackReset)(struct XpkSubIFace *Self, struct XpkSubParams * xpar);
	LONG APICALL (*XpksUnpackChunk)(struct XpkSubIFace *Self, struct XpkSubParams * xpar);
	void APICALL (*XpksUnpackFree)(struct XpkSubIFace *Self, struct XpkSubParams * xpar);
};

#endif /* XPKGZIP_INTERFACE_DEF_H */
