#ifndef INLINE4_XPKGZIP_H
#define INLINE4_XPKGZIP_H

/*
** This file was auto generated by idltool 51.3.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef XPK_XPKSUB_H
#include <xpk/xpksub.h>
#endif

/* Inline macros for Interface "main" */
#define XpksPackerInfo() IXpkSub->XpksPackerInfo() 
#define XpksPackChunk(xpar) IXpkSub->XpksPackChunk(xpar) 
#define XpksPackFree(xpar) IXpkSub->XpksPackFree(xpar) 
#define XpksPackReset(xpar) IXpkSub->XpksPackReset(xpar) 
#define XpksUnpackChunk(xpar) IXpkSub->XpksUnpackChunk(xpar) 
#define XpksUnpackFree(xpar) IXpkSub->XpksUnpackFree(xpar) 

#endif /* INLINE4_XPKGZIP_H */
